export const Type = {
  ADD_TO_BASKET: "ADD_TO_BASKET",
  REMOVE_FROM_BASKET: "REMOVE_FROM_BASKET",
  SET_USER: "SET_USER",
  EMPTY_BASKET: "EMPTY_BASKET",
  REMOVE_ITEM_IMMEDIATELY: "REMOVE_ITEM_IMMEDIATELY",
};
